// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyB5uB06wmkFzNOIZOAWt0htHJ1_voexg',
    appId: '1:252312815913:web:1b8067a9b50182f7c60f38',
    messagingSenderId: '252312815913',
    projectId: 'advancedcallrecorder',
    authDomain: 'advancedcallrecorder.firebaseapp.com',
    storageBucket: 'advancedcallrecorder.firebasestorage.app',
    measurementId: 'G-KEEF8S5BZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRWNWnAVhcqtY2RdR3YcnELLm0EVrKpU',
    appId: '1:252312815913:android:77d986d111869555c60f38',
    messagingSenderId: '252312815913',
    projectId: 'advancedcallrecorder',
    storageBucket: 'advancedcallrecorder.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Zl3V1_VmuUIjRP6nEeUUuDdGqrUx5Ug',
    appId: '1:252312815913:ios:3ece2943251d2218c60f38',
    messagingSenderId: '252312815913',
    projectId: 'advancedcallrecorder',
    storageBucket: 'advancedcallrecorder.firebasestorage.app',
    androidClientId: '252312815913-lnjc50precmm4p0985r0i15kmaj3q92g.apps.googleusercontent.com',
    iosClientId: '252312815913-33p1h1r4frijfbvqcp46a0uf4cuv4pev.apps.googleusercontent.com',
    iosBundleId: 'studio.unicom.acr',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Zl3V1_VmuUIjRP6nEeUUuDdGqrUx5Ug',
    appId: '1:252312815913:ios:3ece2943251d2218c60f38',
    messagingSenderId: '252312815913',
    projectId: 'advancedcallrecorder',
    storageBucket: 'advancedcallrecorder.firebasestorage.app',
    androidClientId: '252312815913-lnjc50precmm4p0985r0i15kmaj3q92g.apps.googleusercontent.com',
    iosClientId: '252312815913-33p1h1r4frijfbvqcp46a0uf4cuv4pev.apps.googleusercontent.com',
    iosBundleId: 'studio.unicom.acr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyB5uB06wmkFzNOIZOAWt0htHJ1_voexg',
    appId: '1:252312815913:web:21d4b11fc8f2265dc60f38',
    messagingSenderId: '252312815913',
    projectId: 'advancedcallrecorder',
    authDomain: 'advancedcallrecorder.firebaseapp.com',
    storageBucket: 'advancedcallrecorder.firebasestorage.app',
    measurementId: 'G-2RXCQQWQZW',
  );
}
